# Call this script from a build directory.
# It creates proxy Makefile that inlcudes Makefile from the source directory.
#

echo Build environment configuration BASH script.

CWD=`pwd`
echo Current working directory=$CWD

SOURCE_PATH="$(dirname ${BASH_SOURCE[0]})"
echo Source path=$SOURCE_PATH

ABS_SOURCE_PATH=$(realpath $SOURCE_PATH)
echo Absolute Source path=$ABS_SOURCE_PATH



#MAKEFILE="Makefile"
#touch $MAKEFILE

#echo "include $MAKE_CONFIG" > $MAKEFILE
#echo "-include custom.config.makefile" >> $MAKEFILE
#echo "include $SOURCE_PATH/bld/Makefile" >> $MAKEFILE

MAKE_CONFIG="config.makefile"
touch $MAKE_CONFIG
echo "# Autogenerated MAKE configuration" > $MAKE_CONFIG
echo "SOURCE_PATH:=$SOURCE_PATH" >> $MAKE_CONFIG

BUILD_HOME=$CWD
echo "BUILD_HOME:=$BUILD_HOME" >> $MAKE_CONFIG

GCC_PATH=`which gcc`
echo GCC=$GCC_PATH
echo "GCC:=$GCC_PATH" >> $MAKE_CONFIG

VERILATOR_PATH=`which verilator`
echo VERILATOR=$VERILATOR_PATH
echo "VERILATOR:=$VERILATOR_PATH" >> $MAKE_CONFIG

IVERILOG_PATH=`which iverilog`
echo IVERILOG=$IVERILOG_PATH
echo "IVERILOG:=$IVERILOG_PATH" >> $MAKE_CONFIG

ICARUS_VVP_PATH=`which vvp`
echo ICARUS_VVP=$ICARUS_VVP_PATH
echo "ICARUS_VVP:=$ICARUS_VVP_PATH" >> $MAKE_CONFIG

# At last include custom configuration.
echo "-include custom.config.makefile" >> $MAKE_CONFIG

