%# SM CAD tools setup:
%# >source /tools/eda_config/startup/dv.common.bashrc 
%# >module load sha
%# >module list


% questa = {ver: '10.3', base: '/tools/mentor/questa'}
% questa[:home] = "#{questa[:base]}/#{questa[:ver]}/questasim"
% questa[:bin] = "#{questa[:home]}/linux_x86_64"

% cadnrc = {ver: '14.10', base: '/tools/cadence/RC'}
% cadnrc[:home] = "#{cadnrc[:base]}/RC#{cadnrc[:ver]}"
% cadnrc[:bin] = "#{cadnrc[:home]}/bin/rc"

installed:
  ruby:
    path: /tools/local/ruby-2.1.0/bin/ruby
  gcc:
    path: /tools/local/gcc-4.9.2/bin/gcc
  verilator:
    vlog: /tools/local/verilator-3.864/bin/verilator
  questa:
    version: &questaVer   <%=questa[:ver]%>
    base   : &questaBase  <%=questa[:base]%>
    home   : &questaHome  <%=questa[:home]%>
    bin    : &questaBin   <%=questa[:bin]%>
    vlog   : &questaVlog  <%=questa[:bin]%>/vlog
    vsim   : &questaVsim  <%=questa[:bin]%>/vsim
    vlib   : &questaVlib  <%=questa[:bin]%>/vlib
    vopt   : &questaVopt  <%=questa[:bin]%>/vopt
    license: >
      1717@sv13.smi.local:1717@sv7.smi.local:1717@sv6.smi.local:1717@sv5.smi.local:1717@sv20.smi.local:
      1717@sv15.smi.local:1717@sv21.smi.local:1717@sv24.smi.local:1717@sv14.smi.local:
      1717@sv4.smi.local:1717@sv3.smi.local:1717@sge1.smi.local:1717@sv18.smi.local:
      1717@sv1.smi.local:1717@sv19.smi.local
  cadnrc:
    bin    : &cadnrcBin <%=cadnrc[:bin]%>
    license: '5280@sv3.smi.local'

# List of Verilog compilers
Verilog:
- verilator
- questa

Synthesis:
- cadnrc

